export const VIEW_PLACES = "VIEW_PLACES";
export const VIEW_ACTIVITIES = "VIEW_ACTIVITIES";
export const FETCH_PLACES = "FETCH_PLACES";
export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const OPEN_MENU = "VIEW_MENU";
export const CLOSE_MENU = "CLOSE_MENU";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
