export const VIEW_PLACES = "VIEW_PLACES";
export const VIEW_ACTIVITIES = "VIEW_ACTIVITIES";
export const VIEW_ACTIVITY = "VIEW_ACTIVITY";
export const VIEW_PROFILE = "VIEW_PROFILE";
export const FETCH_PLACES = "FETCH_PLACES";
export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const OPEN_MENU = "OPEN_MENU";
export const CLOSE_MENU = "CLOSE_MENU";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAIL = "UPLOAD_FAIL";

export const GET_GEOLOCATION = "GET_GEOLOCATION";
